---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: koop-craigslist
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: craigslist
    spec:
      containers:
      - name: koop-craigslist
        image: dmfenton/koop-craigslist
        env:
        - name: KOOP_SERVER_PORT
          value: "80"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: craigslist
  labels:
    app: craigslist
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: craigslist
