apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: koop-craigslist
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: koop-craigslist
    spec:
      containers:
      - name: koop-craigslist
        image: dmfenton/koop-craigslist
        env:
        - name: KOOP_SERVER_PORT
          value: "80"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
        imagePullPolicy: Always
